In [1]:
print('hello')

hello


In [2]:
set1:set = {1,2,3,4,5,5,6,6,7,7,9,9,}
set = {99,81,77,66,9,9,7}
set1.add(18)
set1


{1, 2, 3, 4, 5, 6, 7, 9, 18}

In [3]:
for i in set1:
    print(i)

1
2
3
4
5
6
7
9
18


In [7]:
import numpy as np

# ndarray 是import numpy 後產生的新的處理資料類型
array1:np.ndarray = np.array(range(1,10))
array1 +10*50
# array 方便對整個list運算


array([501, 502, 503, 504, 505, 506, 507, 508, 509])

In [3]:
import numpy    as np
display(np.arange(1.1,4,0.1))
display(np.linspace(1,2,30))


array([1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3,
       2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6,
       3.7, 3.8, 3.9])

array([1.        , 1.03448276, 1.06896552, 1.10344828, 1.13793103,
       1.17241379, 1.20689655, 1.24137931, 1.27586207, 1.31034483,
       1.34482759, 1.37931034, 1.4137931 , 1.44827586, 1.48275862,
       1.51724138, 1.55172414, 1.5862069 , 1.62068966, 1.65517241,
       1.68965517, 1.72413793, 1.75862069, 1.79310345, 1.82758621,
       1.86206897, 1.89655172, 1.93103448, 1.96551724, 2.        ])